config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "home_pages#index"
  get "search", to: "search#search"

  resources :categories, only:[:show] do
    resources :posts, only:[:show]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    case user.role
      when "admin"
        can :access, :rails_admin
        can :dashboard
        can :manage, :all
      when "member"
        can :read, :post
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :posts

  extend FriendlyId
  friendly_id :name, use: [:slugged]
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category, touch: true
  extend FriendlyId
  friendly_id :title, use: [:slugged]
  searchkick text_start: [:content]

  scope :newest_by_desc, -> { order "created_at DESC" }
  scope :newest_by_id, -> { order "posts.id DESC" }
  scope :posts_of_category, -> (category_id){ where category_id: category_id }
  scope :view_of_post, -> { order "posts.view DESC" }
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def role_enum
    ["admin", "member"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@categories = Category.all
  	@current_category = Category.friendly.find params[:id]
    @posts = @current_category.posts
    @right_bar_posts = Post.posts_of_category(@current_category).view_of_post.limit(4)
    @recent_posts = Post.all.view_of_post.limit(5)
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
  	# select Posts of category, Posts.newest
  	

  	# @posts_of_scents = Post.where category: 2
    # @newest_scents = @posts_of_scents.newest_by_id.limit(4)

    # @scents = Category.second.posts.newest_by_id.limit(4)
    @categories = Category.all
  	@newest_posts = Post.newest_by_id.limit(3)
    
    @scent = Category.find_by name: "Scent"
    @scent_newest_posts = Post.posts_of_category(@scent.id).newest_by_id.limit(3)

  	@fashion = Category.find_by name: "Fashion"
  	@fashion_newest_posts = Post.posts_of_category(@fashion.id).newest_by_id.limit(3)

  	@hair = Category.find_by name: "Hair"
  	@hair_newest_posts = Post.posts_of_category(@hair.id).newest_by_id.limit(2)

    @grooming = Category.find_by name: "Grooming"

  	@food = Category.find_by name: "Food & Drink"

  	@others = Category.find_by name: "Others"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  	@categories = Category.all
  	@current_category = Category.friendly.find params[:category_id]
  	@current_post = Post.friendly.find params[:id]
    @right_bar_posts = Post.posts_of_category(@current_category).view_of_post.limit(4)
    @recent_posts = Post.all.view_of_post.limit(5)

  	# increase_view when reload
    # @current_post.increment!(:view) or increment_view
    increment_view
  end

  private

  def increment_view
    session_id = request.session_options[:id]
    is_increment = false

    if session_id.present?
      session[:view_post] = {} unless session[:view_post]

      if (session_id != session[:view_post]["post_id_#{@current_post.id}"])
        is_increment = true
        session[:view_post]["post_id_#{@current_post.id}"] = session_id
      end
    else
      is_increment = true
    end

    @current_post.increment!(:view) if is_increment
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@categories = Category.all
    @recent_posts = Post.all.view_of_post.limit(5)

    # if params[:search].present?
    #   @posts = Post.search(params[:search])
    # else
    #   @posts = []
    # end

    if params[:search].nil?
      @posts = []
    else
      @posts = Post.search params[:search]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_kaminari.html.erb
<div class="row">
	<div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
		<ul class="pagination">
			<li class="disabled"><a href="#">&laquo;</a></li>
			<li class="active"><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">&raquo;</a></li>
		</ul>
	</div>
</div>

app/views/categories/_right_bar.html.erb
<div class="col-md-3 sticky-parent">
	<div class="sidebar" id="sticky_item">
		<%= render "search/form", cached: true %>
		
		<% if @right_bar_posts.present? %>
		<div class="side animate-box">
		  <h2 class="sidebar-heading"><%= t".p" %></h2>
		  <% @right_bar_posts.each do |post| %>
		  <% cache post do %>
			<div class="f-blog">
				<a class="blog-img" style="background-image: url('<%= post.image.url %>');"></a>
				<div class="desc">
					<h3><a><%= link_to post.title, category_post_path(post.category, post) %></a></h3>
					<p class="admin"><span><%= post.created_at.strftime(t".time") %></span></p>
				</div>
			</div>
		  <% end %>
		  <% end %>
		</div>
		<% end %>

		<div class="side animate-box">
			<h2 class="sidebar-heading"><%= t".r" %></h2>
            <% @recent_posts.each do |post| %>
            <% cache post do %>
			<div class="f-blog">
				<a class="blog-img" style="background-image: url('<%= post.image.url %>');"></a>
				<div class="desc">
					<h3><a><%= link_to post.title, category_post_path(post.category, post) %></a></h3>
					<p class="admin"><span><%= post.created_at.strftime(t".time") %></span></p>
				</div>
			</div>
			<% end %>
			<% end %>
		</div>

		<div class="side animate-box">
			<div class="form-group">
				<input type="text" class="form-control form-email text-center" id="email" placeholder="Enter your email">
				<button type="submit" class="btn btn-primary btn-subscribe"><%= t".s" %></button>
			</div>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div id="colorlib-main">
	<div class="colorlib-blog">
		<div class="container-wrap">
			<div class="row">
				<div class="col-md-9">
					<% cache @current_category do %>
					<div class="content-wrap">
						<% @current_category.posts.each do |post| %>
						<article class="blog-entry-travel animate-box">
							<div class="blog-img" style="background-image: url('<%= post.image.url %>');"></div>
							<div class="desc">
								<p class="meta">
									<span class="cat"><a><%= @current_category.name %></a></span>
									<span class="date"><%= post.created_at.strftime(t".time") %></span>
								</p>
								<h2><%= link_to post.title, category_post_path(@current_category, post) %></h2>
								<p><%= post.description %></p>
								<p><a href="single.html" class="btn btn-primary with-arrow">Read More <i class="icon-arrow-right22"></i></a></p>
							</div>
						</article>
						<% end %>
					</div>
					<% end %>
				</div>
				<%= render "right_bar", cached: true %>
			</div>
			<%= render "kaminari", cached: true %>
		</div>
	</div>
</div>

app/views/home_pages/343.html.erb
<div class="col-md-5">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url(https://images.unsplash.com/photo-1551028719-00167b16eac5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=375&q=80);">
			<div class="desc text-center">
				<p class="tag"><span>Sports</span></p>
				<h2 class="head-article"><a href="single.html">Boxing Sports</a></h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-7">
	<div class="row">
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1441984344779-4716bd9e6b04?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=821&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Place</span></p>
						<h2 class="head-article"><a href="single.html">Nature</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1546367260-0d4ec8a3e349?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Place</span></p>
						<h2 class="head-article"><a href="single.html">Nature</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="col-md-6">
	<div class="row">
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1544006593-1a0b9255782d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=744&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>auto</span></p>
						<h2 class="head-article"><a href="single.html">BMW i8</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1506915925765-ed31516b9080?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Sports</span></p>
						<h2 class="head-article"><a href="single.html">Boxing Sports</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1547553641-a18afbab3c96?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Place</span></p>
						<h2 class="head-article"><a href="single.html">Nature</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-md-6">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url(https://images.unsplash.com/photo-1512303712963-792b49bff940?ixlib=rb-1.2.1&auto=format&fit=crop&w=621&q=80);">
			<div class="desc text-center">
				<p class="tag"><span>Healthy</span></p>
				<h2 class="head-article"><a href="single.html">Gym Fitness</a></h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
			</div>
		</div>
	</div>
</div>


<div class="col-md-5">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url(https://images.unsplash.com/photo-1523532855831-190c384cb39a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=889&q=80);">
			<div class="desc text-center">
				<p class="tag"><span>Sports</span></p>
				<h2 class="head-article"><a href="single.html">Boxing Sports</a></h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-7">
	<div class="row">
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1526947425960-945c6e72858f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Place</span></p>
						<h2 class="head-article"><a href="single.html">Nature</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url(https://images.unsplash.com/photo-1519735777090-ec97162dc266?ixlib=rb-1.2.1&auto=format&fit=crop&w=815&q=80);">
					<div class="desc text-center">
						<p class="tag"><span>Place</span></p>
						<h2 class="head-article"><a href="single.html">Nature</a></h2>
						<p>Even the all-powerful Pointing has no control about</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home_pages/_fashion.html.erb
<div class="col-md-6">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @fashion.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @fashion.name, category_path(@fashion) %></a></h2>
				<p><%= @fashion.description %></p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-6">
	<div class="row">
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= @fashion_newest_posts.first.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @fashion.name %></span></p>
						<h2 class="head-article"><a><%= link_to @fashion_newest_posts.first.title, category_post_path(@fashion, @fashion_newest_posts.first) %></a></h2>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= @fashion_newest_posts.second.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @fashion.name %></span></p>
						<h2 class="head-article"><a><%= link_to @fashion_newest_posts.second.title, category_post_path(@fashion, @fashion_newest_posts.second) %></a></h2>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= @fashion_newest_posts.last.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @fashion.name %></span></p>
						<h2 class="head-article"><a><%= link_to @fashion_newest_posts.last.title, category_post_path(@fashion, @fashion_newest_posts.last) %></a></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home_pages/_hair.html.erb
<div class="col-md-7">
	<div class="row">
		<% @hair_newest_posts.each do |post|  %>
		<% cache post do %>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= post.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @hair.name %></span></p>
						<h2 class="head-article"><a><%= link_to post.title, category_post_path(@hair, post) %></a></h2>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<% end %>
	</div>
</div>
<div class="col-md-5">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @hair.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @hair.name, category_path(@hair) %></a></h2>
				<p><%= @hair.description %></p>
			</div>
		</div>
	</div>
</div>

app/views/home_pages/_scent.html.erb
<div class="col-md-6">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @scent.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @scent.name, category_path(@scent) %></a></h2>
				<p><%= @scent.description %></p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-6">
	<div class="row">
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url'<%= @scent_newest_posts.first.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @scent.name %></span></p>
						<h2 class="head-article"><a><%= link_to @scent_newest_posts.first.title, category_post_path(@scent, @scent_newest_posts.first) %></a></h2>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= @scent_newest_posts.second.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @scent.name %></span></p>
						<h2 class="head-article"><a><%= link_to @scent_newest_posts.second.title, category_post_path(@scent, @scent_newest_posts.second) %></a></h2>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="blog-entry animate-box">
				<div class="blog-img blog-img2" style="background-image: url('<%= @scent_newest_posts.last.image.url %>');">
					<div class="desc text-center">
						<p class="tag"><span><%= @scent.name %></span></p>
						<h2 class="head-article"><a><%= link_to @scent_newest_posts.last.title, category_post_path(@scent, @scent_newest_posts.last) %></a></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home_pages/_under_categories.html.erb
<div class="col-md-4">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @food.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @food.name, category_path(@food) %></a></h2>
				<p><%= @food.description %></p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-4">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @grooming.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @grooming.name, category_path(@grooming) %></a></h2>
				<p><%= @grooming.description %></p>
			</div>
		</div>
	</div>
</div>
<div class="col-md-4">
	<div class="blog-entry animate-box">
		<div class="blog-img" style="background-image: url('<%= @others.image.url %>');">
			<div class="desc text-center">
				<h2 class="head-article"><a><%= link_to @others.name, category_path(@others) %></a></h2>
				<p><%= @others.description %></p>
			</div>
		</div>
	</div>
</div>

app/views/home_pages/index.html.erb
<div id="colorlib-main">
	<aside id="colorlib-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
			<% @newest_posts.each do |post| %>
			<% cache post do %>
		   	<li style="background-image: url('<%= post.image.url %>');">
		   		<div class="overlay"></div>
		   		<div class="container-fluid">
		   			<div class="row">
			   			<div class="col-md-12 col-xs-12 js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<div class="desc">
			   						<p class="tag"><span><%= post.category.name %></span></p>
				   					<h1><a><%= link_to post.title, category_post_path(post.category, post) %></a></h1>
				   					<p><%= post.description %></p>
								</div>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		   	<% end %>
		   	<% end %>  	
		  	</ul>
	  	</div>
	</aside>


	<div class="colorlib-blog">
		<div class="container-wrap">
			<div class="row">
				<%= render "fashion", cached:true %>

				<%= render "hair", cached:true %>

				<%= render "scent", cached:true %>

				<%= render "under_categories", cached:true %>
			</div>
		</div>
	</div>			
</div>

app/views/layouts/_side_bar.html.erb
<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
<aside id="colorlib-aside" role="complementary" class="js-fullheight">
	<h1 id="colorlib-logo"><a href="index.html">Males In Town</a></h1>
	<nav id="colorlib-main-menu" role="navigation">
		<ul>
		  <% if @current_category %>
		    <li><a><%= link_to "Home", root_path %></a></li>
		    <% @categories.each do |category| %>
		      <% if @current_category.name == category.name %>
			    <li class="colorlib-active"><a><%= link_to category.name, category_path(category) %></a></li>
		      <% else %>
			    <li><a><%= link_to category.name, category_path(category) %></a></li>
			  <% end %>
			<% end %>
		  <% else %>
			<li class="colorlib-active"><a><%= link_to "Home", root_path %></a></li>
			<% if @categories %>
			<% @categories.each do |category| %>
			  <li><a><%= link_to category.name, category_path(category) %></a></li>
			<% end %>
			<% end %>
		  <% end %>
		</ul>
	</nav>

	<div class="colorlib-footer">
		<p><small>This template is made with <i class="fas fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></small></p>
		<ul>
			<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
			<li><a href="#"><i class="fab fa-twitter"></i></a></li>
			<li><a href="#"><i class="fab fa-instagram"></i></a></li>
			<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
		</ul>
	</div>
</aside>

app/views/posts/_comments.html.erb
<div class="row row-bottom-padded-md">
	<div class="col-md-12 animate-box">
		<h2 class="heading-2">23 Comments</h2>
		<div class="review">
   		<div class="user-img" style="background-image: url(images/person1.jpg)"></div>
   		<div class="desc">
   			<h4>
   				<span class="text-left">Jacob Webb</span>
   				<span class="text-right">24 May 2018</span>
   			</h4>
   			<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>
   			<p class="star">
					<span class="text-left"><a href="#" class="reply"><i class="fas fa-reply"></i></a></span>
   			</p>
   		</div>
   	</div>
	</div>
</div>

app/views/posts/_form_comments.html.erb
<div class="row">
	<div class="col-md-12 animate-box">
		<h2 class="heading-2">Say something</h2>
		<form action="#">
			<div class="row form-group">
				<div class="col-md-6">
					<!-- <label for="fname">First Name</label> -->
					<input type="text" id="fname" class="form-control" placeholder="Your firstname">
				</div>
				<div class="col-md-6">
					<!-- <label for="lname">Last Name</label> -->
					<input type="text" id="lname" class="form-control" placeholder="Your lastname">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="email">Email</label> -->
					<input type="text" id="email" class="form-control" placeholder="Your email address">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="subject">Subject</label> -->
					<input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="message">Message</label> -->
					<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" value="Post Comment" class="btn btn-primary">
			</div>
		</form>	
	</div>
</div>

app/views/search/_form.html.erb
<div class="side animate-box">
	<%= form_tag search_path, method: :get, class: "form-group" do %>
		<%= text_field_tag :search, params[:search], class: "form-control", id: "search", placeholder: "Enter to search...", autocomplete: "off" %>
		<button type="submit" class="btn submit btn-primary">
			<i class="fas fa-search"></i>
			<% submit_tag name: nil %>
		</button>
	<% end %>
</div>

app/views/search/search.html.erb
<div id="colorlib-main">
	<div class="colorlib-blog">
		<div class="container-wrap">
			<div class="row">
				<div class="col-md-9">
					<% if @posts %>
					<div class="content-wrap">
						<% @posts.each do |post| %>
						<% cache post do %>
						<article class="blog-entry-travel animate-box">
							<div class="blog-img" style="background-image: url(images/blog-8.jpg);"></div>
							<div class="desc">
								<p class="meta">
									<span class="cat"><a><%= post.category.name %></a></span>
									<span class="date"><%= post.created_at.strftime(t".time") %></span>
								</p>
								<h2><%= link_to post.title, category_post_path(post.category, post) %></h2>
								<p><%= post.description %></p>
								<p><a href="single.html" class="btn btn-primary with-arrow">Read More <i class="icon-arrow-right22"></i></a></p>
							</div>
						</article>
						<% end %>
						<% end %>
					</div>
					<% else %>
						<h2>Your search did not match any posts.</h2>
					<% end %>
				</div>
				<%= render "categories/right_bar", cached: true %>
			</div>
			<%= render "categories/kaminari", cached: true %>
		</div>
	</div>
</div>